baseURL = 'https://zaccaria-af.github.io/'
languageCode = 'en-us'
title = 'Zaccaria Al-Fatlawi'
theme = 'm10c'

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1

  [[menu.main]]
    identifier = 'tags'
    name = 'Tags'
    url = '/tags'
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = 'Zaccaria Al-Fatlawi'
  description = 'Documenting my learnings in the world of Artificial Intelligence'
  avatar = '/assets/Gentoo-penguin.jpg'
  favicon = '/assets/Gentoo-penguin.jpg'

  [[params.social]]
    icon = 'github'
    name = 'GitHub'
    url = 'https://github.com/zaccaria-af'

  [[params.social]]
    icon = 'twitter'
    name = 'Twitter'
    url = 'https://twitter.com/zaccariaaf'

  [params.style]
    darkestColor = '#d35050'
    darkColor = '#212121'
    lightColor = '#f5e3e0'
    lightestColor = '#f5f5f5'
    primaryColor = '#ffffff'
